import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/templateCode/Header";
import { Providers } from "./providers";
import {AuthProvider} from "./sessionProvider";
import { Toaster } from "react-hot-toast";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
        <Header />
        <Providers>
        <div className="pt-16">{children}</div>
        </Providers>
        <Toaster/>
        {/* <Footer /> */}
        {/* <ScrollToTop /> */}
        </AuthProvider>
      </body>
    </html>
  );
}
